/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialOffersRouteImport } from './routes/special-offers'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayRouteImport } from './routes/pay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTradingRouteImport } from './routes/admin.trading'
import { Route as AdminSpecialOffersRouteImport } from './routes/admin.special-offers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPaymentVerificationRouteImport } from './routes/admin.payment-verification'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInvestmentsRouteImport } from './routes/admin.investments'
import { Route as AdminIncomeRouteImport } from './routes/admin.income'

const SpecialOffersRoute = SpecialOffersRouteImport.update({
  id: '/special-offers',
  path: '/special-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTradingRoute = AdminTradingRouteImport.update({
  id: '/admin/trading',
  path: '/admin/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpecialOffersRoute = AdminSpecialOffersRouteImport.update({
  id: '/admin/special-offers',
  path: '/admin/special-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentVerificationRoute =
  AdminPaymentVerificationRouteImport.update({
    id: '/admin/payment-verification',
    path: '/admin/payment-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvestmentsRoute = AdminInvestmentsRouteImport.update({
  id: '/admin/investments',
  path: '/admin/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIncomeRoute = AdminIncomeRouteImport.update({
  id: '/admin/income',
  path: '/admin/income',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/special-offers': typeof SpecialOffersRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payment-verification': typeof AdminPaymentVerificationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-offers': typeof AdminSpecialOffersRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/special-offers': typeof SpecialOffersRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payment-verification': typeof AdminPaymentVerificationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-offers': typeof AdminSpecialOffersRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/income': typeof IncomeRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/special-offers': typeof SpecialOffersRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payment-verification': typeof AdminPaymentVerificationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/special-offers': typeof AdminSpecialOffersRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/income'
    | '/login'
    | '/pay'
    | '/profile'
    | '/referral'
    | '/register'
    | '/special-offers'
    | '/admin/income'
    | '/admin/investments'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payment-verification'
    | '/admin/settings'
    | '/admin/special-offers'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/income'
    | '/login'
    | '/pay'
    | '/profile'
    | '/referral'
    | '/register'
    | '/special-offers'
    | '/admin/income'
    | '/admin/investments'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payment-verification'
    | '/admin/settings'
    | '/admin/special-offers'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/income'
    | '/login'
    | '/pay'
    | '/profile'
    | '/referral'
    | '/register'
    | '/special-offers'
    | '/admin/income'
    | '/admin/investments'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payment-verification'
    | '/admin/settings'
    | '/admin/special-offers'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IncomeRoute: typeof IncomeRoute
  LoginRoute: typeof LoginRoute
  PayRoute: typeof PayRoute
  ProfileRoute: typeof ProfileRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  SpecialOffersRoute: typeof SpecialOffersRoute
  AdminIncomeRoute: typeof AdminIncomeRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentVerificationRoute: typeof AdminPaymentVerificationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpecialOffersRoute: typeof AdminSpecialOffersRoute
  AdminTradingRoute: typeof AdminTradingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/special-offers': {
      id: '/special-offers'
      path: '/special-offers'
      fullPath: '/special-offers'
      preLoaderRoute: typeof SpecialOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trading': {
      id: '/admin/trading'
      path: '/admin/trading'
      fullPath: '/admin/trading'
      preLoaderRoute: typeof AdminTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/special-offers': {
      id: '/admin/special-offers'
      path: '/admin/special-offers'
      fullPath: '/admin/special-offers'
      preLoaderRoute: typeof AdminSpecialOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-verification': {
      id: '/admin/payment-verification'
      path: '/admin/payment-verification'
      fullPath: '/admin/payment-verification'
      preLoaderRoute: typeof AdminPaymentVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/investments': {
      id: '/admin/investments'
      path: '/admin/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof AdminInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/income': {
      id: '/admin/income'
      path: '/admin/income'
      fullPath: '/admin/income'
      preLoaderRoute: typeof AdminIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IncomeRoute: IncomeRoute,
  LoginRoute: LoginRoute,
  PayRoute: PayRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  SpecialOffersRoute: SpecialOffersRoute,
  AdminIncomeRoute: AdminIncomeRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentVerificationRoute: AdminPaymentVerificationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpecialOffersRoute: AdminSpecialOffersRoute,
  AdminTradingRoute: AdminTradingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
