/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayRouteImport } from './routes/pay'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MarketsCoinIdRouteImport } from './routes/markets.$coinId'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTradingRouteImport } from './routes/admin.trading'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInvestmentsRouteImport } from './routes/admin.investments'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsCoinIdRoute = MarketsCoinIdRouteImport.update({
  id: '/$coinId',
  path: '/$coinId',
  getParentRoute: () => MarketsRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTradingRoute = AdminTradingRouteImport.update({
  id: '/admin/trading',
  path: '/admin/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvestmentsRoute = AdminInvestmentsRouteImport.update({
  id: '/admin/investments',
  path: '/admin/investments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/markets/$coinId': typeof MarketsCoinIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/markets/$coinId': typeof MarketsCoinIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/markets/$coinId': typeof MarketsCoinIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/markets'
    | '/notifications'
    | '/pay'
    | '/profile'
    | '/referral'
    | '/register'
    | '/admin/investments'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/wallets'
    | '/markets/$coinId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/markets'
    | '/notifications'
    | '/pay'
    | '/profile'
    | '/referral'
    | '/register'
    | '/admin/investments'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/wallets'
    | '/markets/$coinId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/markets'
    | '/notifications'
    | '/pay'
    | '/profile'
    | '/referral'
    | '/register'
    | '/admin/investments'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/wallets'
    | '/markets/$coinId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PayRoute: typeof PayRoute
  ProfileRoute: typeof ProfileRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTradingRoute: typeof AdminTradingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$coinId': {
      id: '/markets/$coinId'
      path: '/$coinId'
      fullPath: '/markets/$coinId'
      preLoaderRoute: typeof MarketsCoinIdRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trading': {
      id: '/admin/trading'
      path: '/admin/trading'
      fullPath: '/admin/trading'
      preLoaderRoute: typeof AdminTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/investments': {
      id: '/admin/investments'
      path: '/admin/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof AdminInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketsRouteChildren {
  MarketsCoinIdRoute: typeof MarketsCoinIdRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsCoinIdRoute: MarketsCoinIdRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PayRoute: PayRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTradingRoute: AdminTradingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
